name: Deployment Workflow

on:
  push:
    tags:
    - '*'

jobs:
  deployment:
    runs-on: self-hosted
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Image registry login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: joaorodriguesjr
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Container image build
      uses: docker/build-push-action@v2
      with:
        file: docker/dockerfile
        context: .
        tags: ghcr.io/joaorodriguesjr/fasting:${{ github.ref_name }}
        push: true

    - name: Container image name substitution
      run: sed -i 's#CONTAINER_IMAGE#ghcr.io/joaorodriguesjr/fasting:${{ github.ref_name }}#' kubernetes/deployment.yml

    - name: Containers orchestration
      run: microk8s.kubectl apply -f kubernetes

    - name: Version rollout
      run: microk8s.kubectl rollout restart deployment.apps/fasting-frontend
